### PR TITLE
Proposed starting point

### PR DESCRIPTION
**Pull request by Sqeaky**
This builds but might not do everything ever other Jagati package does.

### CODE REVIEW

**Comment by MakoEnergy** [comment]
You seem to have some zealous copy pasta on line 34 of the root CMakeLists.txt.

**Comment by MakoEnergy** [comment]
The Readme.md seems to have gained a cmake configuration.  Bold strategy.

**Comment by MakoEnergy** [comment]
BitFieldTools looks good logic-wise, but a couple minor styling gripes come to mind.
1) The newlines above and below the datatypes.h inclusion directive(lines 47 and 49).  I don't see any constructive value for them.  I DO see the value in indenting, just not the vertical spacing.
2) The access specifiers in classes/structs aren't worth their own indentation level, in my opinion.  They account for only 1-3 lines per class/struct and not giving them their own indentation level helps us reclaim horizontal space (which I know you value more than I do).

**Comment by MakoEnergy** [comment]
My styling comments for BitFieldTools can be said of Streamlogging.h as well.  In addition:
1) Line 102 (which is a comment) seems to have suffered from some zealous copy pasta.
2) Minor styling gripe, but I feel when masking the visibility of the operation is improved when there are spaces on either side of the operator.  In fact I do this with most operators in executing code.  It's helped me with replace operations, improved visibility, and avoids issues like the super arrow operator.  That said, the masking done in the LogLevel enum may benefit from some spaces.

**Comment by MakoEnergy** [comment]
Lines 106 and 107 of loggingtests.h are using a TEST macro instead of a TEST_EQUAL.  Also, should the filename be camel cased?

**Comment by Sqeaky** [comment]
Cool, I see these and I will Make changes to correct these later today.

**Comment by Sqeaky** [comment]
Fixed - line 34 of the root CMakeLists.txt. 
Fixed - Extra Cmake in ReadMe. Good catch, I feel sloppy letting that through
Moving back access specifier and indented stuff

Reverting the file logging tests.

I will also try adding some CI to this so that we can have more assurance that this works in the general case.

**Pull request merged**
